version: '3.8'
services:
  db:
    container_name: 'postgres'
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=jakwywioze
      - POSTGRES_PASSWORD=jakwywioze
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    container_name: 'spring-boot-backend'
    build:
      context: ../jakwywioze-backend
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jakwywioze
      - SPRING_DATASOURCE_USERNAME=jakwywioze
      - SPRING_DATASOURCE_PASSWORD=jakwywioze
      - SPRING_SESSION_JDBC_INITIALIZE_SCHEMA=always
      - BASE_FRONTEND_URL=http://localhost:80
      - EMAIL=jakwywioze@gmail.com
      - PASSWORD=mfuunbwozssnuesp
    depends_on:
      - db
  frontend:
    container_name: 'vue-frontend'
    build:
      context: ../jakwywioze-frontend
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:8081
    ports:
      - '80:80'
    depends_on:
      - backend
volumes:
  db:
    driver: local
