version: '3.8'
services:
  db:
    container_name: 'postgres'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=jakwywioze
      - POSTGRES_PASSWORD=jakwywioze
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    container_name: 'spring-boot-backend'
    build:
      context: ./backend
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jakwywioze
      - SPRING_DATASOURCE_USERNAME=jakwywioze
      - SPRING_DATASOURCE_PASSWORD=jakwywioze
      - SPRING_SESSION_JDBC_INITIALIZE_SCHEMA=always
    depends_on:
      - db
  frontend:
    container_name: 'vue-frontend'
    build:
      context: ./frontend
    ports:
      - '8080:8080'
    depends_on:
      - backend
  nginx:
    container_name: 'nginx-proxy'
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  db:
    driver: local
